config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  resources :users do
    resources :albums, :only => [:index, :show, :update, :destroy]
  end

  post '/users/:id/albums' => 'albums#create', as: 'album_search'
  get '/auth/spotify/callback' => 'sessions#create'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/album.rb
class Album < ApplicationRecord
    # Album instance relationships
    belongs_to :user
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    # User instance relationships
    has_many :albums
    has_many :artists, through: :albums
    has_many :genres, through: :albums
  end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  
  #Append callback before any controller function runs
  
  before_action :set_user

  # Show all albums
  def index
    if current_user == nil
      redirect_to root_path
    else
      respond_to do |format|
        format.html
        format.json { render json: @user.albums }
        #If the request wants an HTML page, format.html.
        #If the request wants application/json, format.json.
      end
    end
  end

  # Create new album
  def create
    @album = @user.albums.build(album_params)
    if @album.save
      render json: @album
    end
  end

  # Show album details
  def show
    @album = Album.find(params[:id])
    
    render json: @album
  end

  private

  # Sets current user
  #private method for callback
  def set_user
    @user = current_user
  end

  # Acceptable album params
  #whitelist
  def album_params
    params.require(:album).permit(:name, :artist, :release_date, :external_url, :image_url)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Spotify API connection gem
  RSpotify::authenticate("7e196ee602664010b6d29c4df510d260", "604d0619f0814dd3b70efa53803c027e")

  # User log in verification
  def authentication_required
    if !logged_in?
      redirect_to root_path
    end
  end

  # Logged In Check
  def logged_in?
    !!current_user
  end

  # Return current user helper method
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  # Create new session
  def create
    spotify_user = RSpotify::User.new(request.env['omniauth.auth'])

    if User.exists?(email: spotify_user.email)
      @user = User.find_by(email: spotify_user.email)
      @user.credentials = spotify_user.credentials.token
      @user.save

    else
      @user = User.new(email: spotify_user.email, username: spotify_user.id, credentials: spotify_user.credentials.token)
      @user.save
    end

    session[:user_id] = @user.id
    
    redirect_to user_albums_path(@user)

  end

  # Log out
  def destroy
    reset_session
    redirect_to root_path
  end

  private

  # Spotify OmniAuth verification
  def auth
    request.env['omniauth.auth']
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  # Verify user before showing single page of web app
  def home
   
     
    end
  

  private

  # Find and set current user
  def current_user
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<!--Title-->
<h1 class="title" id="main_title">In The Wav.</h1>

<div id="main">
  <div id="grid">
    <!--Add Album Section-->
    <div id="album_add_container">
      <h5>Add Album</h5>
        <div class='form'>
          <%= form_tag(album_search_url(@user), {:id => 'search_form'}) do %>
            <%= text_field_tag :search %>
            <%= hidden_field_tag 'credentials', current_user.credentials %>
            <%= submit_tag "Search", class: 'button', data: { disable_with: false } %>
          <% end %>
        </div>
      <!--Search Results-->
      <div id="search_results">
        <ul id="search_results_list">
        </ul>
      </div>
    </div>

    <!--Album List-->
    <div id="album_list_container">
      <ul id="album_list">
        <% if current_user.albums.empty? %>
          <img src="https://media.giphy.com/media/3xU22GnGEP2r6/giphy.gif" height='125' width='125'>
          <img src="https://media.giphy.com/media/5yLgocnSlDKgWymJ5fi/giphy.gif" height='125' width='125'>
          <img src="https://media.giphy.com/media/ukqOBz4W0ApnDLUw23/giphy.gif" height='125' width='125'>
          <img src="https://media.giphy.com/media/3qskbFZJ0Z9q0b1rfY/giphy.gif" height='125' width='125'>
          <img src="https://media.giphy.com/media/UsGbPVVuNBoMo/giphy.gif" height='125' width='125'>
          <img src="https://media.giphy.com/media/1dMMbcYiO40OX6e8zm/giphy.gif" height='125' width='125'>
          <img src="https://media.giphy.com/media/9xyVBrgWR3aA2BAHLX/giphy.gif" height='125' width='125'>
          <img src="https://media.giphy.com/media/NPSBznfytOtCo/giphy.gif" height='125' width='125'>
          <img src="https://media.giphy.com/media/WXkgDxZxSeMQo/giphy.gif" height='125' width='125'>
          <img src="https://media.giphy.com/media/fe4dwRw6nZKWDRjMzP/giphy.gif" height='125' width='125'>
          <img src="https://media.giphy.com/media/t7syKPdeSZ8SwhQ1Hz/giphy.gif" height='125' width='125'>
          <img src="https://media.giphy.com/media/28mkBBJuyIEPVRbypT/giphy.gif" height='125' width='125'>
          
        <% else current_user.albums.each do |a| %>
          <li class="albums"><%= link_to (image_tag(a.image_url, :alt => "album_cover", height: "125", width: "125")), [current_user, a], class: "more_info"%></li>
        <% end %>
        <% end %>
      </ul>
    </div>

    <!--Album Info-->
    <div id="album_info_container">
      <div id="show_album">
      </div>
    </div>
  </div>
  <p id="log_out"><%= current_user.username %> ― <%= link_to "Logout", logout_path %> </p>
  <h5> Jonathan Schack </h5>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InTheWav</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag "application" %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  </head>

  <body>
    <h6 id="screen_warning">This web app is intended for desktop sized screens. A mobile version is in the works. Ye be warned.</h6>
    <%= yield %>
  </body>

  <footer>
  
  </footer>
</html>

app/views/static_pages/home.html.erb
<div id="log_in">
    <h1 class="title">In The Wav.</h1>
    <button id="log_in_button"><%= link_to('Log in with Spotify', '/auth/spotify') %></button>
    </div>